export const GIFS_LOADED = 'GIFS_LOADED';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const NEXT_SEARCH_REQUEST = 'NEXT_SEARCH_REQUEST';
export const MORE_GIFS_LOADED = 'MORE_GIFS_LOADED';
export const GIF_INFO_LOADED = 'GIF_INFO_LOADED';

export default {
  GIFS_LOADED,
  MORE_GIFS_LOADED,
  INPUT_CHANGE,
  SEARCH_REQUEST,
  NEXT_SEARCH_REQUEST,
  GIF_INFO_LOADED,
};
